### ISSUE TITLE
Constant Gas reading

### ISSUE THREAD

**Issue by ernesst** [adafruit/Adafruit_CircuitPython_BME680#11]
I've acquired recently an Adafruit BME680, with a Pi Zero W.
During the first day the sensor was able to get a resistance reading for the gas, currently the reading is stuck to 45556 whatever atmosphere is. (I've tried alcohol & black marker)

I'm wondering if it's a bug or the sensor burnt.
As you can see below, the sensors jumped between stuck and reading  and now it seems staying stuck.
![image](https://user-images.githubusercontent.com/11337464/45730097-75762b80-bb95-11e8-90c9-805ea8a6af42.png)
The humidity and temperature reading give a relevant feedback.
I'm not recalling specific intervention from me able to act on the resistance reading.

Thanks

**Comment by ernesst** [comment]
Without touching anything the reading went back then collapse for an hours

![image](https://user-images.githubusercontent.com/11337464/45786081-7e6a0a00-bc34-11e8-9ebd-d35ac048bbb0.png)

I'll let it run.

**Comment by caternuson** [comment]
As a comparison check, I ran an UNO with the Arduino lib. I logged data for ~1 hour, breathing on it at the beginning and end to generate a response. Plot of `millis()` vs. `gas_resistance`:
![bme680_uno](https://user-images.githubusercontent.com/8755041/50368224-272d4b80-053b-11e9-9a5d-8dfb7b35fd4e.jpg)
There's a general warming up trend, but it otherwise responded to breath.

I also did a similar check with an Itsy Bitsy M4 and CP 3.1.1. I seemed to have gotten the same odd behavior. Plot of `time.monotonic()` vs. `gas`:
![bme68_itsy](https://user-images.githubusercontent.com/8755041/50368246-69ef2380-053b-11e9-9c46-23501e379b02.jpg)
It initially responded, but then the reading froze. Other readings, like temperature and humidity were still responding.

**Comment by kattni** [comment]
@caternuson Can you test this again? I believe it may have been resolved by #18 based on reference to #12.

**Comment by caternuson** [comment]
@kattni Yep, appears to be fixed. Or at least could not repeat the same behavior as above. Here's latest test result for plot of `gas`:

![image](https://user-images.githubusercontent.com/8755041/79901556-d777c200-83c4-11ea-8683-025105d72f9e.png)

```python
import time
import board
import digitalio
import adafruit_bme680

bme = adafruit_bme680.Adafruit_BME680_I2C(board.I2C())

led = digitalio.DigitalInOut(board.D13)
led.direction = digitalio.Direction.OUTPUT
led.value = False

go = digitalio.DigitalInOut(board.D10)
go.direction = digitalio.Direction.INPUT

print("logging...")
with open("/data.csv", "a") as fp:
    while go.value:
        fp.write("{},{},{},{},{}\n".format(time.monotonic(),
                                           bme.temperature,
                                           bme.gas,
                                           bme.humidity,
                                           bme.pressure))
        fp.flush()
        led.value = not led.value
        time.sleep(1)
print("DONE.")

```

**Comment by kattni** [comment]
Resolved. Closing.
